name: terminal_one
description: "Terminal.One Project"
publish_to: 'none'
version: 0.1.1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  lucide_icons: ^0.257.0
  flutter_secure_storage: ^9.2.4
  http: ^1.5.0
  shared_preferences: ^2.5.3
  provider: ^6.1.5+1
  device_frame: ^1.4.0
  flutter_native_splash: ^2.4.1
  easy_localization: ^3.0.7
  flutter_html: ^3.0.0
  circular_seek_bar: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
 

flutter:
  uses-material-design: true
  
  assets:
    - assets/background/
    - assets/images/
    - assets/translations/

# Flutter Launcher Icons Konfiguration
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/c2f.png"
  remove_alpha_ios: true # Entfernt Alpha-Kanal für iOS App Store Kompatibilität
  min_sdk_android: 21 # Android 5.0
  web:
    generate: true
    image_path: "assets/images/c2f.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/c2f.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/c2f.png"

# Flutter Native Splash Screen Konfiguration  
flutter_native_splash:
  image: assets/images/c2f_fullscreen.png  # Reduzierte Version (400px)
  color: "#2196F3"      # Light theme primary color (Button-Farbe)
  color_dark: "#90CAF9" # Dark theme primary color (Button-Farbe)
  android: true
  ios: true
  web: true
  android_gravity: center # Zentriert statt bildschirmfüllend
  ios_content_mode: scaleAspectFit # Passt das Bild ein ohne zu beschneiden
  web_image_mode: center # Zentriert für Web
  fullscreen: false # Kein Vollbild für kleineres Bild
